# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#
language: R
sudo: false
cache: packages
latex: false
fortran: false
dist: trusty

#matrix:
#  include:
#    - os: linux
#      dist: trusty
#    - os: osx

r:
  - oldrel
  - release
  - devel
env:
  - _R_CHECK_FORCE_SUGGESTS_=false
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
#  - if [ "$TRAVIS_OS_NAME" = "os" ]; then brew update          ; fi

# Build it like on CRAN
script:
  - R CMD build .
  - R CMD check *tar.gz --as-cran

r_packages:
  - covr

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
