# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and this guide: https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5

language: R
sudo: false
cache: packages
latex: false
fortran: false

matrix:
  include:
    - r: oldrel
      os: linux
      dist: trusty
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sudo apt-get install r-base-dev
    - r: release
      os: linux
      dist: trusty
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sudo apt-get install r-base-dev
      r_packages:
      - covr
      after_success:
      - tar -C .. -xf $PKG_TARBALL
      - Rscript -e 'covr::codecov()'
    - r: devel
      os: linux
      dist: trusty
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sudo apt-get install r-base-dev
    - r: release
      os: osx
      r_packages:
      - Rcpp
      - RcppArmadillo
      before_install:
      - brew update
      - brew install gsl
      - brew install llvm
      - brew install boost
      - brew install homebrew/science/hdf5 --enable-cxx
      - mkdir -p ~/.R
      - cat <<- EOF > ~/.R/Makevars
	        # The following statements are required to use the clang4 binary
	        CC=/usr/local/clang4/bin/clang
	        CXX=/usr/local/clang4/bin/clang++
	        CXX11=/usr/local/clang4/bin/clang++
	        CXX14=/usr/local/clang4/bin/clang++
	        CXX17=/usr/local/clang4/bin/clang++
	        CXX1X=/usr/local/clang4/bin/clang++
	        LDFLAGS=-L/usr/local/clang4/lib
	        # End clang4 inclusion statements
	        EOF
      - export DISPLAY=:99.0
      - ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )&


r_packages:
      - geoR
      - splancs
      - RandomFields
      - RandomFieldsUtils
      - nnls

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

