# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and this guide: https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5
#
language: R
sudo: false
cache: packages
latex: false
fortran: false
#dist: trusty

matrix:
  include:
    - r: oldrel
      os: linux
      dist: trusty
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
    - r: release
      os: linux
      dist: trusty
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      r_packages:
      - covr
      after_success:
      - tar -C .. -xf $PKG_TARBALL
      - Rscript -e 'covr::codecov()'
    - r: devel
      os: linux
      dist: trusty
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
    - r: release
      os: osx
      osx_image: xcode7.3
      r_packages:
      - Rcpp
      - RcppArmadillo
      before_install:
      - brew update
#      - brew upgrade
#      - brew cask reinstall xquartz
#      - brew install tcl-tk --with-tk
#      - brew link --overwrite --force tcl-tk; brew unlink tcl-tk
#      - export DISPLAY=:99.0
#      - ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )&

#r:
#  - oldrel
#  - release
#  - devel



env:
  - _R_CHECK_FORCE_SUGGESTS_=false

# before_install:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok ) & fi
#  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start          ; fi

# r_packages:
#   - covr
#
# after_success:
#   - tar -C .. -xf $PKG_TARBALL
#   - Rscript -e 'covr::codecov()'
