# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#
language: R
sudo: false
cache: packages
dist: trusty
r:
  - oldrel
  - release
  - devel
env:
  - _R_CHECK_FORCE_SUGGESTS_=false
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
r_packages:
  - covr

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
