# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and this guide: https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5

language: R
sudo: false
cache: packages
latex: false
fortran: false

matrix:
  include:
    - r: oldrel
      os: linux
      dist: bionic
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sudo apt-get install r-base-dev
    - r: release
      os: linux
      dist: bionic
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sudo apt-get install r-base-dev
      r_packages:
      - covr
      after_success:
      - tar -C .. -xf $PKG_TARBALL
      - Rscript -e 'covr::codecov()'
    - r: devel
      os: linux
      dist: bionic
      before_install:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sudo apt-get install r-base-dev
      - sudo apt install libgsl-dev
      r_packages:
      - gsl
    - r: release
      os: osx
      r_packages:
      - ps
      - digest
      - Rcpp
      - RcppArmadillo
      before_install:
      - brew update
      - brew install gsl
      - export DISPLAY=:99.0
      - ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )&


r_packages:
      - geoR
      - splancs
      - RandomFields
      - RandomFieldsUtils
      - nnls

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

