// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pix2angC
NumericMatrix pix2angC(int Nside, bool Nest, Rcpp::Nullable<Rcpp::IntegerVector> spix);
RcppExport SEXP rcosmo_pix2angC(SEXP NsideSEXP, SEXP NestSEXP, SEXP spixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type Nside(NsideSEXP);
    Rcpp::traits::input_parameter< bool >::type Nest(NestSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type spix(spixSEXP);
    __result = Rcpp::wrap(pix2angC(Nside, Nest, spix));
    return __result;
END_RCPP
}
