

#### CURRENTLY THE DATA USED IN THE PLOT FUNCTION IS TOO LARGE FOR CRAN ##
#' Plot CMB Data
#'
#' This function produces a plot from a CMB Data Frame.
#'
#'@param cmbdf a CMB Data Frame with either spherical or cartesian coordinates.
#'@param add if TRUE then this plot will be added to any existing plot
#'@param sample.size optionally specifies the size of a simple random
#'sample to take before plotting. This can make the plot less
#'computationally intensive
#'
#'@return
#'A plot of the CMB data
#'
#'@examples
#' df <- CMBDataFrame("CMB_map_smica1024.fits")
#' plot(df, sample.size = 800000)
#'
#'@export
plot.CMBDataFrame <- function(cmbdf, add = FALSE, sample.size, ...)
{

  if ( nside(cmbdf) == 1024 )
  {
    if ( missing(sample.size) )
    {
      cols <- CMBcols1024 # internal data generated by data-raw/ColourMap.R
    } else {
      spix <- sample(pix(cmbdf), sample.size)
      cmbdf <- cmbdf[spix,]
      cols <- CMBcols1024[spix]
    }

    warning(paste("(development stage) the colour map for",
            "nside = 1024 may not be ideal"))

  } else if ( nside(cmbdf) == 2048 ) {

    ## The following code must be replaced to work with nside = 2048
    if ( missing(sample.size) )
    {
      cols <- CMBcols1024 # internal data generated by data-raw/ColourMap.R
    } else {
      spix <- sample(pix(cmbdf), sample.size)
      cmbdf <- cmbdf[spix,]
      cols <- CMBcols1024[spix]
    }

    warning(paste("(development stage) the colour map used was not",
            "generated for nside = 2048"))
  }

  coords <- coords(cmbdf)

  try(if(coords != "spherical" && coords != "cartesian")
    stop("Coordinates must be spherical or cartesian"))

  if (coords == "spherical") {
    cmbdf_xyz <- as.data.frame(sphereplot::sph2car(cmbdf$long,
                                                   cmbdf$lat,
                                                   deg = FALSE))
  } else {
    # Else coords are already cartesian
    cmbdf_xyz <- data.frame(x = cmbdf$x, y = cmbdf$y, z = cmbdf$z)
  }

  rgl::open3d()
  rgl::bg3d("black")
  rgl::plot3d(cmbdf_xyz, col = cols, type = "p", cex = 5,
              pch = 3, box = FALSE, axes = FALSE, add = add)
}


#' Summarise CMB Data
#'
#' This function produces a summary from a CMB Data Frame.
#'
#'@param cmbdf a CMB Data Frame.
#'
#'@return
#'A summary of the CMB data.
#'
#'@examples
#' df <- CMBDataFrame("CMB_map_smica1024.fits", sample.size = 800000)
#' summary(df)
#'
#'@export
summary.CMBDataFrame <- function(cmbdf)
{
  if ( sum(names(df) == "I") %>% as.numeric() %>% identical(1) )
  {
    ans <- list(intensities = summary(df$I))
  }

  ans[["coords"]] <- ifelse(is.null(coords(cmbdf)),
                            "HEALPix only",coords(cmbdf))
  ans[["ordering"]] <- ordering(cmbdf)
  ans[["nside"]] <- nside(cmbdf)
  ans[["window"]] <- "The CMBWindow class is under development"

  ans
}


#' Print CMB Data
#'
#' This function neatly prints the contents of a CMB Data Frame.
#'
#'@param cmbdf a CMB Data Frame.
#'
#'@return
#'Prints contents of the CMB data frame to the console.
#'
#'@examples
#' df <- CMBDataFrame("CMB_map_smica1024.fits", sample.size = 800000)
#' print(df)
#' df
#'
#'@export
print.CMBDataFrame <- function(cmbdf)
{
  print(tibble::as.tibble(cmbdf))
}





